name: fermitools-fermi-env-testing
channels:
  - conda-forge
  - fermi
  - threeml
  - astropy 
dependencies:
  - "python-tzdata==2025.3"
  - python=3.11
  - aplpy
  - pytest
  - astromodels 
  - threeml==2.4.3
  - junit-xml
  - astropy
  - astropy-iers-data
  - ipykernel 
  - nb_conda_kernels
  - "gammapy==2.0.*"
  - pgplot
  - healpy
  - jupyter
  - jupyter_server
  - libpng
  - "matplotlib==3.9.*"
  - "numpy==1.26.*"
  - conda-forge::nbmake
  - scipy
  - pmw
  - seaborn
  - "fermitools==2.5.*"
  - "fermitools-data"
  - pyregion
  - pytest-xdist
