name: fermitools-fermi-env-testing
channels:
  - conda-forge
  - fermi
  - threeml
  - astropy 
dependencies:
  # - "python-tzdata==2025.3"
  # - setuptools<82
  - python=3.11
  - aplpy
  - pytest
  - astromodels 
  - threeml
  - junit-xml
  - astropy
  - astropy-iers-data
  - ipykernel 
  - nb_conda_kernels
  - gammapy
  - pgplot
  - healpy
  - jupyter
  - jupyter_server
  - libpng
  - matplotlib
  - "numpy==1.26.*"
  - conda-forge::nbmake
  - scipy
  - pmw
  - seaborn
  - "fermitools==2.5.*"
  - "fermitools-data"
  - "fermipy=1.4.1"
  - pyregion
  - pytest-xdist
