name: fermibottle linux ci 
on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - '**.md'
      - .clang-format
      - .dockerignore
      - .gitignore
      - docker-compose.yml
      - Dockerfile
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'

env:
  TEST_TAG: fssc/fermibottle_lite
  LATEST_TAG: fermi-lat/fermibottle2026:latest
  DATE: 2026.05.08 #$(date +'%m-%d-%Y')

jobs:
  build_docker:
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false  # Runs all matrix combinations even if some fail
      matrix:
        platform: [amd64, arm64]
        include:
          - platform: amd64
            runner: ubuntu-24.04
          - platform: arm64
            runner: ubuntu-24.04-arm

    steps:
      - name: Checkout FermiBottle repository
        uses: actions/checkout@v6
        with:
          path: $GITHUB_WORKSPACE/FermiBottle # Clones to $GITHUB_WORKSPACE/FermiBottle

      # - name: Set current date
      #  run: "echo \"DATE=$(date +'%m-%d-%Y')\"" >> $GITHUB_ENV

      - name: Run tests from ScienceTools against FermiBottle
        uses: actions/checkout@v6
        with:
          repository: fermi-lat/ScienceTools # Specify the other repo's name
          path: ScienceTools # Clones to $GITHUB_WORKSPACE/ScienceTools

      # - name: Use Docker in rootless mode.
      #  uses: ScribeMD/rootless-docker@0.2.2

      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # - name: Set up QEMU
      #  uses: docker/setup-qemu-action@v3

      - name: Check inside
        id: confirm_inside_env
        run: |
           echo "look around  jsa"
           pwd
           ls -l

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
        # with:
        #  buildkitd-flags: --debug

      # - name: Build and TEST
      #   uses: docker/build-push-action@v7
      #  with:
      #    context: $GITHUB_WORKSPACE/FermiBottle/docker
      #    platforms: linux/arm64 
      #    load: true
      #    push: true
      #    tags: ${{ env.TEST_TAG }}
      #    # file: ./docker/Dockerfile 4,linux/arm64, linux/amd64

      - name: Build and push Docker image
        run: |
          # $GITHUB_WORKSPACE/FermiBottle/docker
          docker build --platform linux/${{ matrix.platform }} -t ${{ env.TEST_TAG }}-${{ matrix.platform }}:${{ env.DATE }} -f docker/Dockerfile .
          docker push ${{ env.TEST_TAG }}-${{ matrix.platform }}

      - name: Run Test script in container
        # -v mounts the current workspace to /app inside the container
        # -w sets the working directory inside the container
        run: |
          docker run \
            -w /home/fermi \
            ${{ env.TEST_TAG }} \
            sh ./test_fermibottle.sh

#      - name: Build and push
#        uses: docker/build-push-action@v7
#        with:
#          platforms: linux/amd64,linux/arm64
#          load: true
#          push: false
#          tags: ${{ env.LATEST_TAG }}
